# Generated by Django 3.1.3 on 2020-11-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='link',
        ),
    ]
