# Generated by Django 3.1.3 on 2020-11-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0002_remove_destination_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rideshare',
            old_name='schedule',
            new_name='date_and_time',
        ),
    ]
