# Generated by Django 3.1.3 on 2020-11-19 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0003_auto_20201114_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideshare',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rideshare',
            name='number_of_passengers',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
