# Generated by Django 3.1.3 on 2020-11-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0005_driver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
